CREATE TABLE users (
	id	integer GENERATED BY DEFAULT ON NULL AS IDENTITY,
	created_at	date NOT NULL,
	updated_at	date NOT NULL,
	email	varchar2('100') DEFAULT '',
	encrypted_password	varchar2('100') DEFAULT '',
	reset_password_token	varchar2('100'),
	reset_password_sent_at	date,
	remember_created_at	date,
	confirmation_token	varchar2('100'),
	confirmed_at	date,
	confirmation_sent_at	date,
	unconfirmed_email	varchar2('100'),
	type	varchar2('100') DEFAULT 'User',
	first_name	varchar2('100'),
	last_name	varchar2('100'),
	PRIMARY KEY(id)
);

CREATE TABLE badges (
	id	integer GENERATED BY DEFAULT ON NULL AS IDENTITY,
	name	varchar2('100'),
	picture_file	varchar2('100') DEFAULT 'badge.jpg',
	rule_name	varchar2('100'),
	rule_parameter	varchar2('100'),
	created_at	date NOT NULL,
	updated_at	date NOT NULL,
	PRIMARY KEY(id)
  -- ++++++
);

CREATE TABLE users_badges (
	id number NOT NULL,
	badge_id number NOT NULL,
	user_id	number NOT NULL,
	created_at date NOT NULL,
	updated_at date NOT NULL,
  CONSTRAINT fk_rails_3b48e1eb65 FOREIGN KEY(user_id) REFERENCES users(id),
	PRIMARY KEY(id),
	CONSTRAINT fk_rails_b366c671bb FOREIGN KEY(badge_id) REFERENCES badges(id)
);

CREATE TABLE questions (
	id	integer NOT NULL,
	title	varchar2('100') NOT NULL,
	created_at	date NOT NULL,
	updated_at	date NOT NULL,
	test_id	integer,
	CONSTRAINT fk_rails_cb4b358d50 FOREIGN KEY(test_id) REFERENCES tests(id),
	PRIMARY KEY(id)
  -- ++++++
);

CREATE TABLE gists (
	id	integer NOT NULL,
	url	varchar2('100'),
	user_id	integer NOT NULL,
	question_id	integer NOT NULL,
	CONSTRAINT fk_rails_6038c85e3c FOREIGN KEY(question_id) REFERENCES questions(id),
	CONSTRAINT fk_rails_b015781927 FOREIGN KEY(user_id) REFERENCES users(id),
	PRIMARY KEY(id)
  -- ++++++
);

CREATE TABLE categories (
	id	integer GENERATED BY DEFAULT ON NULL AS IDENTITY,
	title	varchar2('100') NOT NULL,
	created_at	date NOT NULL,
	updated_at	date NOT NULL,
	PRIMARY KEY(id)
  -- ++++++
);

CREATE TABLE answers (
	id	integer NOT NULL,
	correct	number(1, 0) DEFAULT 0,
	created_at	date NOT NULL,
	updated_at	date NOT NULL,
	question_id	integer,
	title	varchar2('100') NOT NULL,
	PRIMARY KEY(id),
	CONSTRAINT fk_rails_3d5ed4418f FOREIGN KEY(question_id) REFERENCES questions(id)
  -- ++++++
);

CREATE TABLE tests (
	id	integer NOT NULL,
	title	varchar2('100') NOT NULL,
	level	integer DEFAULT 0,
	created_at	date NOT NULL,
	updated_at	date NOT NULL,
	category_id	integer,
	author_id	integer,
	timer	integer,
  PRIMARY KEY(id),
	CONSTRAINT fk_rails_d58c5057b2 FOREIGN KEY(author_id) REFERENCES users(id),
	CONSTRAINT fk_rails_cda342dc0a FOREIGN KEY(category_id) REFERENCES categories(id)
);

CREATE TABLE test_passages (
	id	integer NOT NULL,
	user_id	integer NOT NULL,
	test_id	integer NOT NULL,
	current_question_id	integer,
	correct_questions	integer DEFAULT 0,
	created_at	date NOT NULL,
	updated_at	date NOT NULL,
	successful	number(1, 0) DEFAULT 0,
	PRIMARY KEY(id),
	CONSTRAINT fk_rails_1c4bb70cb0 FOREIGN KEY(current_question_id) REFERENCES questions(id),
	CONSTRAINT fk_rails_57c9aa48e7 FOREIGN KEY(test_id) REFERENCES tests(id),
	CONSTRAINT fk_rails_11c1f136b6 FOREIGN KEY(user_id) REFERENCES users(id)
);